name: Pull Request Checks

on:
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_tests:
    name: Cargo Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Check version update
      run: |
        git fetch origin main
        OLD_VERSION=$(git show origin/main:Cargo.toml | grep -m 1 "version" | sed 's/.*"\(.*\)".*/\1/')
        CURRENT_VERSION=$(grep -m 1 "version" Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
        
        if [ "$OLD_VERSION" == "$CURRENT_VERSION" ]; then
          echo "Error: Version in Cargo.toml has not been updated."
          echo "Current version: $CURRENT_VERSION"
          echo "Version needs to be incremented in the PR."
          exit 1
        fi
        
        echo "Version updated from $OLD_VERSION to $CURRENT_VERSION"
    
    - name: Run Clippy
      run: cargo clippy -- -D warnings
    
    - name: Run tests
      run: cargo test --verbose
      env:
        RUST_BACKTRACE: 1